### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by anilone** [quantosapplications/flutter_provider_utilities#2]
/D:/src/flutter/.pub-cache/git/flutter_provider_utilities-3fb9c88d7e83f3fd2664ebdc1c3745e784b5766f/lib/src/listeners/message_listener.dart:105:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'MessageListener<T>'.
 - 'MessageListener' is from 'package:flutter_provider_utilities/src/listeners/message_listener.dart' ('/D:/src/flutter/.pub-cache/git/flutter_provider_utilities-3fb9c88d7e83f3fd2664ebdc1c3745e784b5766f/lib/src/listeners/message_listener.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.

      ScaffoldMessenger.of(context)
      ^^^^^^^^^^^^^^^^^
/D:/src/flutter/.pub-cache/git/flutter_provider_utilities-3fb9c88d7e83f3fd2664ebdc1c3745e784b5766f/lib/src/listeners/message_listener.dart:132:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'MessageListener<T>'.

 - 'MessageListener' is from 'package:flutter_provider_utilities/src/listeners/message_listener.dart' ('/D:/src/flutter/.pub-cache/git/flutter_provider_utilities-3fb9c88d7e83f3fd2664ebdc1c3745e784b5766f/lib/src/listeners/message_listener.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
      ScaffoldMessenger.of(context)
      ^^^^^^^^^^^^^^^^^

**Comment by ftognetto** [comment]
Hello, I reverted the package to use Scaffold.of instead of ScaffoldMessenger. That's not in stable yet
